[build]
  publish = "public"
[functions]
  node_bundler = "esbuild"
[functions."index"]
  included_files = ["templates/*.html"]
[functions."thumbnail"]
  external_node_modules = ["chrome-aws-lambda"]
[dev]
  NODE_ENV = "development"
  framework = "#custom"
  command = "npm run spaces-dev-netlify"
  targetPort = 8080
  port = 8000
[context.production]
  NODE_ENV= "production"
[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
[[redirects]]
from = "/thumbnail/*"
to = "/.netlify/builders/thumbnail"
status = 200
force = true
[[redirects]]
from = "/*"
to = "/.netlify/builders/index"
status = 200