[build]
  publish = "public"
[functions]
  node_bundler = "esbuild"
[functions.index]
  included_files = ["public/aesthetic.computer/disks/**/*.mjs",
                    "public/aesthetic.computer/dep/**/*.mjs",
                    "public/aesthetic.computer/lib/**/*.mjs"]
[functions.thumbnail]
  external_node_modules = ["chrome-aws-lambda"]
[dev]
  NODE_ENV = "development"
  framework = "#custom"
  command = "npm run spaces-dev-netlify"
  targetPort = 8080
  port = 8000
[context.production]
  NODE_ENV= "production"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
[headers.values]
  Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "/thumbnail/*"
  to = "/.netlify/builders/thumbnail"
  status = 200
[[redirects]]
  from = "/*"
  to = "/.netlify/builders/index"
  status = 200